CREATE DATABASE IF NOT EXISTS comfort
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE comfort;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','manager','editor','translator','dealer') NOT NULL DEFAULT 'editor',
  avatar VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id CHAR(36) PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  name JSON NOT NULL,
  description JSON NOT NULL,
  image VARCHAR(500) NOT NULL,
  parent_id CHAR(36) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS collections (
  id CHAR(36) PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  name JSON NOT NULL,
  description JSON NOT NULL,
  image VARCHAR(500) NOT NULL,
  style VARCHAR(80) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id CHAR(36) PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  sku VARCHAR(80) NOT NULL UNIQUE,
  name JSON NOT NULL,
  description JSON NOT NULL,
  category_id CHAR(36) NOT NULL,
  collection_id CHAR(36) NOT NULL,
  images JSON NOT NULL,
  model_url VARCHAR(500) NULL,
  video_url VARCHAR(500) NULL,
  height DECIMAL(10,2) NOT NULL DEFAULT 0,
  width DECIMAL(10,2) NOT NULL DEFAULT 0,
  depth DECIMAL(10,2) NOT NULL DEFAULT 0,
  length DECIMAL(10,2) NOT NULL DEFAULT 0,
  material VARCHAR(160) NOT NULL,
  finish VARCHAR(160) NOT NULL,
  colors JSON NOT NULL,
  textures JSON NOT NULL,
  specs JSON NOT NULL,
  downloads JSON NOT NULL,
  price INT NOT NULL DEFAULT 0,
  featured TINYINT(1) NOT NULL DEFAULT 0,
  availability ENUM('in_stock','limited','preorder') NOT NULL DEFAULT 'in_stock',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
  CONSTRAINT fk_products_collection FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS projects (
  id CHAR(36) PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  title JSON NOT NULL,
  description JSON NOT NULL,
  location JSON NOT NULL,
  year SMALLINT NOT NULL,
  images JSON NOT NULL,
  before_image VARCHAR(500) NULL,
  after_image VARCHAR(500) NULL,
  video_url VARCHAR(500) NULL,
  product_ids JSON NOT NULL,
  category VARCHAR(80) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blog_posts (
  id CHAR(36) PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  title JSON NOT NULL,
  excerpt JSON NOT NULL,
  content JSON NOT NULL,
  cover_image VARCHAR(500) NOT NULL,
  category VARCHAR(80) NOT NULL,
  tags JSON NOT NULL,
  author JSON NOT NULL,
  published_at DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media_assets (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('image','video','pdf','glb','usdz','texture') NOT NULL,
  url VARCHAR(500) NOT NULL,
  folder VARCHAR(160) NOT NULL DEFAULT 'uploads',
  size INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(80) NULL,
  company VARCHAR(160) NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS calculator_projects (
  id CHAR(36) PRIMARY KEY,
  user_email VARCHAR(190) NULL,
  input_json JSON NOT NULL,
  result_json JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS certificates (
  id CHAR(36) PRIMARY KEY,
  title JSON NOT NULL,
  issuer VARCHAR(190) NULL,
  year SMALLINT NULL,
  file_url VARCHAR(500) NOT NULL,
  image VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS download_files (
  id CHAR(36) PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  title JSON NOT NULL,
  category VARCHAR(80) NOT NULL DEFAULT 'other',
  url VARCHAR(500) NOT NULL,
  file_size VARCHAR(40) NULL,
  downloadable TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_settings (
  setting_key VARCHAR(80) PRIMARY KEY,
  setting_value JSON NOT NULL
);
